version: 2
jobs:
  deploy:
    docker:
      - image: docker.pkg.github.com/nna774/docker-layer/terraform:latest
    steps:
      - checkout
      - run: ruby make_records.rb | tee generated.tf
      - run: terraform init -backend-config "bucket=nana-terraform-state" -backend-config "key=dark-kuins.net-dns.state" -backend-config "region=ap-northeast-1" -backend-config "access_key=${AWS_ACCESS_KEY}" -backend-config "secret_key=${AWS_SECRET_KEY}"
      - run: terraform version
      - run: terraform plan
      - run: terraform apply -auto-approve
workflows:
  version: 2
  all:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
